### ISSUE TITLE
When Ticket is closed and when reply to that email will re-open the ticket?

### ISSUE THREAD

**Issue by ghost** [jfqd/redmine_helpdesk#101]
When ticket for helpdesk is closed and if we reply to that email will re-open the same ticket?

**Comment by dilipmadake** [comment]
Right now it is not opening the closed ticket if it re-open the closed ticket it will very helpful to us.

**Comment by vilppuvuorinen** [comment]
This would really make sense and probably would not be that difficult to implement. @jfqd: What do you think?

**Comment by dilipmadake** [comment]
Can you please help where we need to change in cron job or in configuration file.

We want to re-open closed ticket? How we can dot it?

**Comment by vilppuvuorinen** [comment]
Sample patch is available at https://www.redmine.org/issues/7994
It looks like the patch is intended for 2.2-ish Redmine releases. I would not recommend blindly patching.

I think a feature like this could make it into master since it seems to fit in the application domain quite well.

**Comment by dilipmadake** [comment]
Thanks for reply,
Confusion, Can we need to patch or you are not recommending?

**Comment by vilppuvuorinen** [comment]
You can take a look at the patch and figure out if you can/want to implement similar patch into your current deployment. There is probably a suitable seam for the patch in this plugins code that could provide that patch in less intrusive way.

**Comment by dilipmadake** [comment]
I tried this patch but it's not working.
My Redmine version is Redmine 2.4.7.stable.14072

**Comment by jfqd** [comment]
This seems to be more a support than an issue request. Please read the [guidelines for contributing](https://github.com/jfqd/redmine_helpdesk/blob/master/CONTRIBUTING.md).

**Comment by jfqd** [comment]
In my point of view the project manager should decide if the ticket need to be opened again or not.

**Comment by vilppuvuorinen** [comment]
From project manager's point of view that does make sense. However, it risks issues getting lost with the 'Closed' status. As we can see here some users want to directly set the status to 'Open' and I can imagine some use cases where it would be good to have a freely configurable third option that could differentiate the closed issues with active support client participation from other issues.

Configurable fields would be
* Status that allows opening on support client participation
* Status that allows changing status from closed->'3rd state'
* '3rd state'
* Status where support client participation has no effect on issue status

Depending on projects workflow the 'Closed' status is not necessarily always the same and for decent consistency the feature would need more design work.

In any case a separate issue would be necessary. Maybe even a separate 'Feature proposal' tag for such issues. At least this issue and the recurring case with email from anonymous user. If nothing else it would keep new issues popping up with the same topic.

**Comment by jfqd** [comment]
OK, I realize that there is a need for this feature. It should be optional to use it.

I personally have no time to write it yet, but would be happy to get a pull request.

**Comment by jfqd** [comment]
Version 0.0.16 has this frature included: Reopening a closed issue is handled if the reopen-closed-issues-by-email checkbox is checked. (optional, per project)
