### ISSUE TITLE
owner-email isn't set

### ISSUE THREAD

**Issue by DemonDomen** [jfqd/redmine_helpdesk#102]
Hello. I'm using Redmine 2.6.6.

I've followed the installation and usage instructions, the issue is added to Redmine, but the owner-email field is always blank. 
The project is public. 

I'm using this command to import the e-mails:
```bash
rake redmine:email:receive_imap RAILS_ENV="production" -f /var/www/redmine/Rakefile host=imap.asdf.com username=test password=xxxxx starttls=true project=test_project move_on_success=read move_on_failure=failed unknown_user=accept
```

**Comment by jfqd** [comment]
Please read the [CONTRIBUTING](https://github.com/jfqd/redmine_helpdesk/blob/master/CONTRIBUTING.md) file why I close this issue.

**Comment by DemonDomen** [comment]
Oh, sorry. Even though this issue is already closed, I'll explain how I solved it:

I added the user Anonymous to the project, with the role Reporter. It wasn't enough for anonymous users to have "Treat user as supportclient" enabled, I had to enable it for Reporter as well. 

Now it works as it should.

**Comment by jfqd** [comment]
Thank you for reporting back your solution. Never had a need for it, but will try it on the next installation of the plugin.
