### ISSUE TITLE
Cron for fetching mail doesn't work.

### ISSUE THREAD

**Issue by AndyIbanez** [jfqd/redmine_helpdesk#103]
The cronjob in the description yields this error whenever it runs:

```/bin/sh: 1: redmine: not found```

I cannot find any information on a redmine CLI command. I have googled "redmine: command not found" with quotation marks and I don't get many results (this is what makes me suspect such command just doesn't exist). Attempting to run ```redmine``` manually gives a similar result:

```redmine: command not found```

What am I supposed to use instead of "redmine"?

My cronjob is basically a copy/paste version of the one in the repo description:

```
*/1 * * * * redmine /usr/bin/rake -f /srv/redmine/Rakefile --silent redmine:email:receive_imap RAILS_ENV="production" host=imap.gmail.com port=993 username=MY_SUPPORT_EMAIL password=MY_SUPPORT_PASSWORD ssl=true project=mignori folder=Mignori move_on_success=processed move_on_failure=failed no_permission_check=1 unknown_user=accept 1 > /dev/null
```

EDIT: You can tell I'm not exactly a cronjob expert. I think the instruction should say "redmineuser" instead of "redmine" to solve this ambiguity.

**Comment by vilppuvuorinen** [comment]
I don't recommend using a cron job at all. Look into latest Redmine documentation for latest recommendations on task running. Initializing the Rails environment every time is flimsy and requires a bit too much muscle from hardware.

Documentation could use some updating though.

**Comment by AndyIbanez** [comment]
Could you please point me to the right direction? I'm googling "redmine scheduled task" but all I'm seeing are plugins. Can this not be done by Redmine anymore? Even if you provide a link to the documentation that mentions how to schedule tasks correctly I will be happy, as I cannot seem to find it.

**Comment by vilppuvuorinen** [comment]
Here's a direct link: http://www.redmine.org/projects/redmine/wiki/RedmineReceivingEmails#Schedule-email-receiving-with-Rufus-Scheduler

**Comment by nixmomo** [comment]
Try that
`*/1 * * * * redmine rake -f /srv/redmine/Rakefile --silent redmine:email:receive_imap RAILS_ENV="production" host=imap.gmail.com port=993 username=MY_SUPPORT_EMAIL password=MY_SUPPORT_PASSWORD ssl=true project=mignori folder=Mignori move_on_success=processed move_on_failure=failed no_permission_check=1 unknown_user=accept 1 > /dev/null
`

This works in Redmine 3.2.

**Comment by jfqd** [comment]
@AndyIbanez thanks for the edit hint, changed the readme.
