### ISSUE TITLE
Owner-email field is empty

### ISSUE THREAD

**Issue by berti92** [jfqd/redmine_helpdesk#104]
How is it possible that your plugin saves the mail address
of a unknown user to the field owner-email?

In my case I've changed the line 21 in mail_handler_patch.rb to "if true"
than it worked.

**Comment by vilppuvuorinen** [comment]
Most likely there is something wrong with the setup or you are trying to create issues into a private project.

**Comment by damac23** [comment]
Hi berti92,
you may have a very resent version of redmine, right?
Maybe this workaround is fitting for you: https://github.com/jfqd/redmine_helpdesk/issues/75#issuecomment-101950450
It's working for me with redmine 3.2.0.

**Comment by maxdevaine** [comment]
Hi,
I have same problem.
"owner-email" field is empty and "copy-to" too.
I have Redmine 3.2.1 on Debian Jessie.
Project is marked as "Public".
I tried solution #75 , but still not working.

I using cronjob to create issue from mail :
`
/usr/local/bin/rake -f /var/www/redmine/Rakefile redmine:email:receive_imap RAILS_ENV="production" host=mailserver.tld username=testsup password=password ssl=true port=993 project=Test tracker=Chyba unknown_user=accept priority=normal status=new no_permission_check=1 no_account_notice=1
`

This help me too :
In my case I've changed the line 21 in mail_handler_patch.rb to "if true"

Max
