### ISSUE TITLE
rdm-mailhandler support

### ISSUE THREAD

**Issue by peterbeck** [jfqd/redmine_helpdesk#107]
Hi there,

this plugin seems to be a great alternative to the anonymous_authors plugin which does not seem to work with 3.2.0 anymore. Are there any plans to support rdm-mailhandler.rb in future ?

Best Regards 
Peter

**Comment by vilppuvuorinen** [comment]
It looks like the somewhat destructive ```alias_method_chain``` usage has finally caught up.

Both ```mail_handler_patch.rb``` and ```mailer_patch.rb``` use ```alias_method_chain``` to replace the corresponding methods with reimplemented logic. While this makes the overall functionality a little easier to reason, it also shifts maintenance burden over to this plugin.

@jfqd: I can't tell for sure if the compatibility issues would be resolved by dropping the reimplemented code, but it would be a good first step. The original issue - if it wasn't related to changes in implementation - could also pop up while refactoring. These changes were suggested in #63 and discussed in #73. I could rebase the changes in cf56f75 on top of the current master with minimal effort and create a new PR.

@peterbeck: Could you provide any logs or further describe the issue? I don't have suitable environment currently available.

**Comment by peterbeck** [comment]
Hi @vilppuvuorinen,

sure I can. The Postfix Alias for Redmine's mailhandler:
```
support: "|/etc/postfix/rdm-mailhandler.rb -v -u http://localhost:80 --unknown-user=accept --no-permission-check -k xy -p foobar -t Support --priority normal -o project,tracker,priority"
```
and redmine's (using 3.2.0) production log:
```
Started POST "/mail_handler" for ::1 at 2015-12-14 09:38:28 +0100
Processing by MailHandlerController#index as HTML
  Parameters: {"key"=>"xy", "email"=>"From xy@example.com  Mon Dec 14 09:38:28 2015\nReturn-Path: <xy@example.com>\nX-Original-To: support@foobar.com\nDelivered-To: support@foobar.com\nReceived: from mail.foobar.com (unxgrp001 [10.42.1.12])\n\tby unxweb002.internal (Postfix) with ESMTP id 573FC591\n\tfor <support@foobar.com>; Mon, 14 Dec 2015 09:38:28 +0100 (CET)\nX-Virus-Scanned: Debian amavisd-new at unxgrp001.internal\nReceived: from mail.foobar.com ([127.0.0.1])\n\tby localhost (unxgrp001.internal [127.0.0.1]) (amavisd-new, port 10024)\n\twith ESMTP id Xf2KpVxO7-9p for <support@foobar.com>;\n\tMon, 14 Dec 2015 09:38:24 +0100 (CET)\ncontent-type: text/plain; charset=\"utf-8\"\nto: support@foobar.com\nUser-Agent: SOGoMail 2.3.3a\nMIME-Version: 1.0\ndate: Mon, 14 Dec 2015 08:38:24 +0000\nsubject: foobar test 2\nmessage-id: <511c-566e8000-1-2efbd700@72648775>\nX-Forward: (null) env=REMOTE_HOST\nfrom: \"User Name\" <xy@example.com>\ncontent-transfer-encoding: 7bit\n\ntest 2\n\n", "allow_override"=>"project,tracker,priority", "unknown_user"=>"accept", "default_group"=>nil, "no_account_notice"=>nil, "no_notification"=>nil, "no_permission_check"=>"1", "project_from_subaddress"=>nil, "issue"=>{"project"=>"foobar", "tracker"=>"Support", "priority"=>"normal"}}
  Rendered mailer/_issue.text.erb (14.7ms)
  Rendered mailer/issue_add.text.erb within layouts/mailer (35.8ms)
  Rendered mailer/_issue.html.erb (7.3ms)
  Rendered mailer/issue_add.html.erb within layouts/mailer (29.2ms)
Completed 500 Internal Server Error in 1259ms (ActiveRecord: 115.1ms)

NoMethodError (undefined method `charset' for nil:NilClass):
  app/models/mail_handler.rb:218:in `receive_issue'
  app/models/mail_handler.rb:175:in `dispatch'
  app/models/mail_handler.rb:150:in `receive'
  app/models/mail_handler.rb:49:in `block in receive'
  app/models/mail_handler.rb:46:in `receive'
  app/controllers/mail_handler_controller.rb:29:in `index'
```
The issue is received in Redmine but still has the "Anonymous" user set and also still appears to be in postfix' mailqueue:
```
573FC591        780 Mon Dec 14 09:38:28  xy@example.com
(temporary failure. Command output: Failed to contact your Redmine server (500). Posting to http://localhost:80/mail_handler... Response received: 500)
                                         support@foobar.com
```
some environment info (system is Debian Jessie):
```
Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
```
helpdesk-send-to-owner-default is set to "Yes", "owner-email" is checked.

Best Regards
Peter

**Comment by peterbeck** [comment]
by th way: there is an error raised at AddTreatAsSupportclientToAnonymous when removing the plugin:
```
/usr/src/redmine-3.2.0/plugins/redmine_helpdesk/db/migrate/005_add_treat_as_supportclient_to_anonymous.rb:7:in `down'
ActiveRecord::RecordNotFound: Couldn't find Role with 'id'=all
```
after commenting the "down" action it works. As far as I know it's not necessarily needed to create a role after installing the plugin as anonymous already has the permission. or am I wrong ?

**Comment by vilppuvuorinen** [comment]
It looks like I did not do my homework on this one. Even the README says that this feature has never worked and probably never will. In addition, there is this one #38.

However, by a quick glance the ```rdm-mailhandler.rb``` seems to work in pretty much exactly same way as the actual SMTP fetch making this look a little bit like a bug. At least this should be marked as a feature proposal as already requested in #38. The logs could also be helpful in the future.
