### ISSUE TITLE
Fetching large messages

### ISSUE THREAD

**Issue by bar-souza** [jfqd/redmine_helpdesk#108]
Hi Guys

Recently I have noticed than large issues recived from email were not fetched by redmine. The message is tagged "failed" at gmail but don't appear in redmine. The last message that was not fetched had about 1800 characters.

 When I tried create a new issue in redmine web interface with the same message, the issue was created without problems.

Anyone had this problem?

Thanks

**Comment by jfqd** [comment]
Always good to know: Redmine version, Ruby version, Plugin version, operating system?

**Comment by bar-souza** [comment]
I'm sorry for lack of information.

Here you go.

Environment:
  Redmine version                3.1.2.stable.14882
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Subversion                     1.8.10
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  redmine_base_deface            0.0.1
  redmine_closes_resolved_issues 1.0.2
  redmine_default_custom_query   1.1.2
  redmine_helpdesk               0.0.15
  redmine_image_clipboard_paste  1.0.0
  redmine_ldap_sync              2.0.7.devel.gba84cac44e
  redmine_lightbox2              0.2.4
  redmine_private_wiki           0.2.2
  redmine_refresh                0.3.1
  redmine_track_control          1.1.0

O.S. is Debian 8

Thank you

**Comment by vilppuvuorinen** [comment]
@bar-souza: Could you provide an example mail that fails to load? Including headers and all. Just replace addresses and emails with some arbitrary data to be sure. Unless Redmine people have got you covered already ofcourse.

**Comment by bar-souza** [comment]
@vilppuvuorinen thanks for helping, please see the one mail example that was rejected  moments ago.

                                                                                                                                                                                                                                                            
>Delivered-To: xxx at xxx.org.br
Received: by 10.36.51.17 with SMTP id k17csp574311itk;
        Fri, 8 Jan 2016 09:56:26 -0800 (PST)
X-Received: by 10.31.148.144 with SMTP id w138mr73307648vkd.44.1452275786781;
        Fri, 08 Jan 2016 09:56:26 -0800 (PST)
Return-Path: <yyy at yyy.com.br>
Received: from yyy.com.br (yyy.com.br. [XXX.XXX.XXX.XXX])
        by mx.google.com with ESMTP id 126si92112252vke.135.2016.01.08.09.56.26
        for <xxx at xxx.org.br>;
        Fri, 08 Jan 2016 09:56:26 -0800 (PST)
Received-SPF: pass (google.com: domain of yyy at yyy.com.br designates 200.144.182.184 as permitted sender) client-ip=XXX.XXX.XXX.XXX;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of yyy at yyy.com.br designates XXX.XXX.XXX.XXX as permitted sender) smtp.mailfrom=yyy at yyy.com.br
Received: from localhost (localhost [127.0.0.1])
	by yyy.com.br (Postfix) with ESMTP id 95D9A1801BB
	for <xxx at xxx.org.br>; Fri,  8 Jan 2016 15:56:25 -0200 (BRST)
X-Virus-Scanned: F-Secure Anti-Virus em yyy.com.br
Received: from yyy.com.br ([127.0.0.1])
	by localhost (yyy.com.br [127.0.0.1]) (amavisd-new, port 10024)
	with ESMTP id 0LFT5VO5kXN8 for <xxx at xxx.org.br>;
	Fri,  8 Jan 2016 15:56:24 -0200 (BRST)
Received: from DESKTOP(xxx.org.br [XXX.XXX.XXX.XXX])
	(Authenticated sender: yyy at yyy.com.br)
	by yyy.com.br (Postfix) with ESMTPA id C9E4D1801B6
	for <xxx at xxx.org.br>; Fri,  8 Jan 2016 15:56:24 -0200 (BRST)
X-Virus-Status: Clean
X-Virus-Scanned: clamav-milter 0.98.7 at yyy.com.br
From: "Ms. YYY" <yyy at yyy.com.br>
To: <xxx at xxx.org.br>
Subject: =?iso-8859-1?Q?Vers=E3o_finalizada_do_Compacto?=
Date: Fri, 8 Jan 2016 15:55:32 -0200
Message-ID: <00be01d14a3d$c4d26bc0$4e774340$at usp.br>
MIME-Version: 1.0
Content-Type: multipart/related;
	boundary="----=_NextPart_000_00BF_01D14A2D.01499BC0"
X-Mailer: Microsoft Outlook 15.0
Thread-Index: AdFKPbB7rLu2a17tS6ea1mfYjR5d6w==
Content-Language: pt-br
This is a multipart message in MIME format.
------=_NextPart_000_00BF_01D14A2D.01499BC0
Content-Type: multipart/alternative;
	boundary="----=_NextPart_001_00C0_01D14A2D.01499BC0"
------=_NextPart_001_00C0_01D14A2D.01499BC0
Content-Type: text/plain;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable
Prezados, verifiquei que parte das altera=E7=F5es (1 e 2 em amarelo) =
j=E1 foram
feitas no Compacto. Obrigada.
=20
Gostaria apenas de lembrar dos outros itens (3 e 4 em verde) que ainda =
n=E3o
foram alterados.=20
=20
Me desculpem o incomodo, mas =E9 que este relat=F3rio em especial, =E9 =
utilizado
como documento anexado aos contratos entre pecuaristas e os maiores
frigor=EDficos, por isso =E9 de fundamental import=E2ncia acertarmos =
todos os
detalhes.
=20
Muitas pessoas t=EAm nos questionado quando o Compacto estar=E1 =
terminado para
que eles possam utilizar a vers=E3o final como documenta=E7=E3o. Se =
quando as
outras altera=E7=F5es estiverem ok puderem, por gentileza, nos avisar, =
poderemos
informar para os agentes.
=20
Muito obrigada,
=20
Shirley
=20
=20
Apenas mais algumas observa=E7=F5es que requerem adequa=E7=E3o no =
compacto:
=20
1)    Seria importante mantermos os valores m=E9dios da coluna Prz L(4) =
em
negrito, assim como ocorre com os valores da coluna Vst L(1). Pode tirar =
o
negrito da coluna VarDiaP(4). J=E1 est=E1 ok
=20
2)      As colunas MinV L(2) e MaxP L(6) est=E3o com o %, sendo que esse
s=EDmbolo deveria aparecer nas colunas de varia=E7=E3o: VarDiaV(1) e =
VarDiaP(4) J=E1
est=E1 ok
=20
=20
3)      Favor tirar a letra =93L=94 nos cabe=E7alhos das colunas =
conforme indicado
abaixo:
=20
Antiga sequ=EAncia dos t=EDtulos: Vst L(1)  VarDiaV(1)  Min V L(2)  Max =
V L(3)
Prz L(4) VarDiaP(4) MinP L(5) MaxP L(6) Pmp(7)
=20
Trocar os t=EDtulos para: Vst(1)    VarDiaV(1)    MinV(2)    MaxV(3)    =
Prz(4)
VarDiaP(4)   MinP(5)   MaxP(6)   Pmp(7)
=20
=20
4)      Favor trocar as notas metodol=F3gicas  no final das tabelas de =
pre=E7os
regionais (das duas p=E1ginas)
=20
Antiga:=20
Notas metodol=F3gicas: * Valores elaborados pelo Cepea a partir de
levantamentos junto a compradores e vendedores do mercado f=EDsico. * =
Valores
com indica=E7=E3o L s=E3o LIVRES de Funrural; aqueles acompanhados por D =
s=E3o para
DESCONTAR o Funrural (2,3%). * As varia=E7=F5es referem-se ao dia =FAtil =
anterior.
A abrevia=E7=E3o  "nd"  significa que n=E3o foi obtido dado, sendo =
usada tamb=E9m
para indicar aus=EAncia de varia=E7=E3o nos casos em que n=E3o houve =
dado no dia
anterior. * Prazo M=E9dio de Pagamento (7): dias para abate dos =
neg=F3cios
captados hoje + dias para pagamento a partir do abate.
=20
Substituir a antiga por:=20
Notas metodol=F3gicas:  Valores elaborados pelo Cepea a partir de
levantamentos junto a compradores e vendedores do mercado f=EDsico. * =
Pre=E7os
livres de Funrural. As varia=E7=F5es referem-se ao dia =FAtil =
anterior.   A
abrevia=E7=E3o  "nd"  significa que n=E3o foi obtido dado para =
divulga=E7=E3o, sendo
usada tamb=E9m para indicar aus=EAncia de varia=E7=E3o nos casos em que =
n=E3o houve
dado no dia anterior. * Prazo M=E9dio de Pagamento (7): dias para abate =
dos
neg=F3cios captados hoje + dias para pagamento a partir do abate.
=20
=20
Atenciosamente,
=20
Ms. YYY
=20
=20
=20

**Comment by vilppuvuorinen** [comment]
I have a feeling that the root cause is in Redmine code, but I'll try to insert this mail as a test fixture and see if it bounces in test harness.

**Comment by vilppuvuorinen** [comment]
I tried receiving that mail in a unit test and everything seemed to work smoothly. The actual SMTP or whatever is used to actually receive the mail is bypassed in this test. As suspected, the plugin does not seem responsible for the failures. I did add the from address to the mail to make verification easier, but I don't think that caused the initial issue.

I used the following setup for the tests:

Redmine version: `3.1.2`
Ruby version: `2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]`
Database adapter: `PostgreSQL`

**Comment by bar-souza** [comment]
@vilppuvuorinen I think I know that was happening. I was running the rake task with normal user, when ran with sudo, the mail that was fetched smoothly.
I suspect that rake was doing some cache in some folder that the common user does not have permission.

Thanks @vilppuvuorinen and @jfqd

**Comment by jfqd** [comment]
Well, you should fix your permissions issue and run the rake task as a regular user :)
