### ISSUE TITLE
attachements truncated in email sent to supportclient

### ISSUE THREAD

**Issue by ettorix** [jfqd/redmine_helpdesk#112]
Hi,
Thank you for your plugin.
I test it and when i add a note in a issue with a attachement, the mail to the supportclient but the attachements are incorrect.
For exemple, when i add the filename 2.jpg (size 188 Ko), in the source message, there is only :

----==_mimepart_56bc4458b0808_42cc1366770135e0
Content-Type: image/jpeg;
 charset=UTF-8;
 filename=2.jpg
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename=2.jpg
Content-ID: <56bc4458b5255_42cc136677013617@***.mail>

/9j/4AAQSkZJRgABAgEASABIAAD/4QfWRXhpZgAATU0AKgAAAAgABwESAAMA
AAABAAEAAAE=

----==_mimepart_56bc4458b0808_42cc1366770135e0--

(the file is truncated)
Do you know what is the problem ?
Thanks

**Comment by ettorix** [comment]
I use 
- redmine 3.2.0
- ruby 2.2.3p173 (2015-08-18 revision 51636) [x64-mingw32]
- Windows 10

**Comment by maxdevaine** [comment]
Hi,
I have same problem, but for incomming email : create issue from email
If email have attachment, then issue is created without attachment and without watchers.
I have Redmine 3.2.1
Do you have same problem with incomming email?

Thank you
Max Devaine

**Comment by ettorix** [comment]
Hi
I don't have the problem with the issues created by email (with a configuration with postfix), only for emails to supportclient  with this plugin. 
Any idea? 
Thank you

**Comment by 1dot44mb** [comment]
@ettorix I came across same problem on Windows. Chances are that you are using Windows too.

You can see why this is happening in the following answer. (See 3rd comment):
http://stackoverflow.com/a/7157218

To solve it;

1. Modify plugins\redmine_helpdesk\lib\helpdesk_mailer.rb
2. Go to line 43;
3. Remove the line:  `attachments[a.filename] = File.read(a.diskfile)`
4. Write this instead: `attachments[a.filename] = File.open(a.diskfile, 'rb') { |f| f.read }`

**Comment by maheshmavathur** [comment]
@ettorix still facing problem with attachments? Let me know! I too had problem with attachments like Broken images and decrease in size  of the files. It is fixed now!

**Comment by jfqd** [comment]
@maheshmavathur It would be helpful for others to know how you fixed it.

**Comment by maheshmavathur** [comment]
I am using 
Redmine helpdesk plugin  0.0.15

In the helpdesk_mailer.rb 
# add any attachements
    ....
      .......
          begin
            attachments[a.filename] = File.binread(a.diskfile) // update this line
         .......
end

Its working for me now!

**Comment by jfqd** [comment]
@ghost Thx. fixed it.
