### ISSUE TITLE
Feature Request: add configurable header to notification emails

### ISSUE THREAD

**Issue by jonnsn** [jfqd/redmine_helpdesk#115]
According to the helpdesk-email-footer there should also be a configurable header to be able to prefix the notification emails with something like:
--- reply below this line to update the issue ----
such a configuration exists in redmine, but I think the helpdesk mails should use a separate one.

This would allow the user to reply to the mails without having redmine appending the actual notification message again and again.

**Comment by jfqd** [comment]
@jonnsn If you are willing to contribute a pull request I will leave this issue open.

**Comment by jonnsn** [comment]
I am not very familiar with ruby. Though if no one else is able and willing to add this, I will try to find some time and dig into it of course.
