### ISSUE TITLE
email sending issues with redmine 3.2.2

### ISSUE THREAD

**Issue by Trikke76** [jfqd/redmine_helpdesk#121]
Hi,
helpdesk-first-reply, helpdesk-email-footer, helpdesk-sender email all have no impact when filled in. Emails are sent from the standard redmine mail adres and a first email is never received by the user.

all other tickets are received fine but from the standard redmine mail address.
Anyone having the same problems or is this related to our redmine 3.2.2 installation 

Environment:
  Redmine version                3.2.2.stable
  Ruby version                   2.0.0-p598 (2014-11-13) [x86_64-linux]
  Rails version                  4.2.5.2
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.7.14
  Git                            1.8.3.1
  Filesystem  
Redmine plugins:
  contracts                      2.1.0
  redmine_dmsf                   1.5.6
  redmine_helpdesk               0.0.15
  redmine_knowledgebase          3.1.0
  redmine_questions              0.0.7
  redmine_timelog_timer          2.0.1
  redmine_work_time              0.3.2

**Comment by tonyivanz** [comment]
same issue for me with 3.2.3

**Comment by DaniilHarun** [comment]
same issue 3.3.1.stable
