### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by RolandSM** [jfqd/redmine_helpdesk#123]
Hello,

i followed your steps but something here in my Redmine 3.3.0 is wrong?
I added in Administration -> Custom Fields for Projects a Boolean with the name "owner-email" and set the view to checkboxes. But i only see the owner-email above the tracker section?
![screenshot-1](https://cloud.githubusercontent.com/assets/16316603/16546492/878d4cd8-414c-11e6-9397-7969b7665981.png)

Is it possible to name the fields in German?

Then i followed further until the cronjob, this works and i got a ticket.
But when i comment the ticket i have no option to send the comment to the user?

I think its because the above field owner-email could not be set correctly?

Thanks for your help.

**Comment by Sh4d0wF1gh7** [comment]
Oh. I have to set this field inside Tickets, not inside the project...

But the option to send mail as in your screenshot is even not here.

**Comment by Sh4d0wF1gh7** [comment]
Today i solved with correct reinstallation the problems and now it works great.
Thank you for this great plugin.

What means the new field "copy-to"?

Is it possible, that a support ticket is assigned to a person?
Or first email when creating a support ticket goes also to a supporter?

Also this one works with private projects is this right?

Greets

**Comment by luisfy** [comment]
Hi, 

I've recently installed the plugin and apparently goes fine (the plugin appears on the admin pannel), but no fields have been aded to the tables of the database. I've tried with others plugins that modiffy the database, as contacts, and these one added multiple tables. Do i have to tell some information about my database to the plugin?

Thanks.
