### ISSUE TITLE
Internal error 500 after updating Issue

### ISSUE THREAD

**Issue by xantyp** [jfqd/redmine_helpdesk#124]
Hello.
I have installed your plugin with Bitnami Redmine (https://bitnami.com/redirect/to/131172/bitnami-redmine-3.3.1-0-windows-installer.exe).
When I want to update any Issue in any Project (for example change state to Closed) it throws 500 Internal error.
After uninstalling your plugin, everything work just fine.
Any idea how to fix it?

**Comment by jfqd** [comment]
Please include a stacktrace of the error. Thx

BTW: If you want to use this plugin Redmine 3.1 is the latest supported for now.

**Comment by xantyp** [comment]
Thanks for quick reply, I use older version.

Sorry I forgot report from log file:
```
Completed 500 Internal Server Error in 31ms (ActiveRecord: 0.0ms)

NoMethodError (undefined method `send_to_owner=' for #<Journal:0x4f1f2c8>):
  plugins/redmine-helpdesk/lib/helpdesk_hooks.rb:25:in `controller_issues_edit_before_save'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:91:in `call_hook'
  app/controllers/issues_controller.rb:514:in `block in save_issue_with_child_records'
  app/controllers/issues_controller.rb:503:in `save_issue_with_child_records'
  app/controllers/issues_controller.rb:179:in `update'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by jfqd** [comment]
As thought the issue is the version of your Redmine.

The plugin need to be made compatible with Redmine 3.3. If you like to jump in to send me a pull request, you are welcome :)

Otherwise you should use Redmine 3.1

**Comment by Q8ake** [comment]
Is there any way to make this plugin compatible to Redmine 3.3 ?
I cannot switch back to Redmine 3.0 (

**Comment by jfqd** [comment]
Yes it is possible to make this plugin compatible to Redmine 3.3. Pull requests welcome.

**Comment by Q8ake** [comment]
I did get your point? what have I to do? I am not so familiar in this case
