### ISSUE TITLE
Project is live?

### ISSUE THREAD

**Issue by jaclas** [jfqd/redmine_helpdesk#127]
Or dead? :(

**Comment by vilppuvuorinen** [comment]
It looks like there are at least a couple of companies or organizations using this plugin. However, there has not been that many active contributors in the past couple of years. PRs with bug fixes or compatibility improvements are still actively merged. New features rarely have any tests with them or even break existing tests and are therefore rarely merged. Additionally the tests suite seems to be currently broken. I've been planning to fix it for quite some time now but this far I haven't had the time to do it.

**Comment by jfqd** [comment]
@jaclas It is up to you. Send in your pull request to fix stuff! Or if you cannot, pay some who can! OpenSource is not free.

**Comment by jaclas** [comment]
@jfqd Some code, others test and report bugs. Everyone does what they can. This is how Open Source works. If it hurts you that nobody is making money transfers for your work, stop creating open source code and do commercial work, then they will pay you.

ps. I don't use Redmine
