### ISSUE TITLE
Compatibility with 3.4.2.stable

### ISSUE THREAD

**Issue by keithkuk** [jfqd/redmine_helpdesk#128]
Compatibility with 3.4.2.stable

Are there any plans to update the plugin to Redmine 3.4.2.stable?

Thanks a lot for your work.

**Comment by jfqd** [comment]
You are invited to send a pull request :)

**Comment by raggajah** [comment]
Hello, i like your helpdesk plugin, thank's a lot.
this question is very intresting for me too, i tried on 3.4.2 - it's not working

**Comment by inpos** [comment]
same here

**Comment by mrejas** [comment]
Installed on 3.4.3. Works somewhat. There seems to be more or less random wether or not a ticket gets data or if it is totally empty (No subject, No email, No body). But sometimes it works.

Is there anyone that have got it working on 3.4.x. I don't have the skills to fix it but it doesn't look impossible to fix this.

**Comment by Bno93** [comment]
are there new infos about updating this plugin to 3.4+

**Comment by jfqd** [comment]
You are welcome to try it out and send a pull request if not.

**Comment by jfqd** [comment]
OK. nobody was sending a pull request. Closing.
