### ISSUE TITLE
Error while adding attachments.

### ISSUE THREAD

**Issue by maheshmavathur** [jfqd/redmine_helpdesk#129]
Plugin works fine for adding notes and adding attachments like .txt and .bat files. Plugin shows error while adding attachments like .jpg,.gif,.pdf,.docx,.doc,.pptx etc. Size of the files are been reduced to bytes and images are showing as broken.
Please update asap. Thank you!
![git1](https://user-images.githubusercontent.com/30690889/29211501-0700c384-7eb7-11e7-97b9-1a77ddc78259.JPG)
![git2](https://user-images.githubusercontent.com/30690889/29211502-0708f482-7eb7-11e7-8445-5527e947b5f4.JPG)

**Comment by jfqd** [comment]
> Please update asap. Thank you!

Sure, you can hire me: https://qutic.com/en/contact/

**Comment by maheshmavathur** [comment]
Sorry I forgot to mention the envi of the tool!
Everything works fine except attachments.

Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.1.9-p490 (2016-03-30) [i386-mingw32]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  event_notifications            3.2.1
  redmine_banner                 0.1.2
  redmine_helpdesk               0.0.15
  redmine_issue_field_visibility 1.0.1
  redmine_local_avatars          1.0.3
  redmine_monitoring_controlling 0.1.1
  redmine_silencer               0.4.1
  redmine_tweaks                 1.0.2
  sidebar_hide                   0.0.8
