### ISSUE TITLE
How to use desk-sender-email?

### ISSUE THREAD

**Issue by valerivp** [jfqd/redmine_helpdesk#140]
What am I doing wrong? I specify help desk-sender-email, but get an email from redmine address.
(https://www.screencast.com/t/1j23UvS8QlG

The helpdesk-first-reply and helpdesk-email-footer fields are also not visible in the email.
https://www.screencast.com/t/gxfKOMWHG4

Redmine 4

**Comment by jfqd** [comment]
Get latest version v0.0.17 from today, maybe this is fixing it. Closing cause of contributing violation.

**Comment by valerivp** [comment]
Does not work
https://www.screencast.com/t/MLftL4tlotR
https://www.screencast.com/t/sSlg5Q5xqt
https://www.screencast.com/t/cGWkCupj
https://www.screencast.com/t/mrYZcssZrs5

**Comment by valerivp** [comment]
![image](https://user-images.githubusercontent.com/28062383/68181612-1944b580-ffa9-11e9-8e2e-347b8dc629e0.png)
