### ISSUE TITLE
Text formatting problems when received reply from supportclient

### ISSUE THREAD

**Issue by jurijstoks** [jfqd/redmine_helpdesk#142]
Hi!

When i send email to supportclient, all works fine, but when supportclient send back reply, it looks like [this](https://drive.google.com/open?id=1lQPFWG3pvYzSciFoX-N0nMziqt5wJGYw). 
Is it possible to fix it? Is there any hope, that it will be fixed?

Otherwise it works well. Thanks a lot for useful plugin!!!

**Comment by jfqd** [comment]
What was the email client sending this email?
