### ISSUE TITLE
Don't autofill owner-email and copy-to

### ISSUE THREAD

**Issue by ghost** [jfqd/redmine_helpdesk#144]
Hello, in the task that is created by email, fields owner-email and copy-to are empty, but in the description I see all email headers.

![image](https://user-images.githubusercontent.com/4963504/69535187-6c989b00-0f8c-11ea-932b-5b669929c6cd.png)

**Comment by arnekaulfuss** [comment]
Wich version of redmine are you using?
Did you do all needed configuration as described here: 
[](https://github.com/jfqd/redmine_helpdesk#usage)

**Comment by sysn-zz** [comment]
Hello arnekaulfuss, thank you for your reply.

Redmine version           4.0.2.stable
Ruby version                 2.5.3-p105 (2018-10-18) [x86_64-linux]
Rails version                  5.2.2

I did all configuration that was needed. If I fill owner-email by myself it works fine.

**Comment by ANemcov** [comment]
Don't autofill too
Environment:
  Redmine version                4.0.3.stable
  Ruby version                   2.6.3-p62 (2019-04-16) [x86_64-linux]
  Rails version                  5.2.2.1

**Comment by ANemcov** [comment]
In file mail_handler_patch.rb:
 at line 32 (need project, but ued issue:

`# any cc handling needed?
          custom_value = custom_field_value(issue.project, 'cc-handling')
          if (!@email.cc.nil?) && (custom_value.value == '1')`

at line 115 (in query params need issue.id, but was issue.project.id:
`def custom_field_value(issue,name)
        custom_field = CustomField.find_by_name(name)
        CustomValue.where(
          "customized_id = ? AND custom_field_id = ?", issue.id, custom_field.id
        ).first
      end`

**Comment by arnekaulfuss** [comment]
it's one more:
[https://github.com/jfqd/redmine_helpdesk/pull/143](https://github.com/jfqd/redmine_helpdesk/pull/143)

**Comment by sysn-zz** [comment]
> it's one more:
> #143

Thank you, it works!

**Comment by sysn-zz** [comment]
> it's one more:
> #143
> 
> I asked just to be sure that it's not something different because my patch is not approved.
> For me its working in my project.

Thank you, it works!

**Comment by jfqd** [comment]
Was fixed today.
