### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by Dmitry-Gal** [jfqd/redmine_helpdesk#146]
rake redmine:plugins:migrate NAME=redmine_helpdesk VERSION=0 RAILS_ENV=production
/var/www/redmine/config/initializers/bypass_ssl_verification.rb:2: warning: already initialized constant OpenSSL::SSL::VERIFY_PEER
== 5 AddTreatAsSupportclientToAnonymous: reverting ============================
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Couldn't find Role with 'id'=all
/var/www/redmine/plugins/redmine_helpdesk/db/migrate/005_add_treat_as_supportclient_to_anonymous.rb:11:in `down'
/var/www/redmine/lib/redmine/plugin.rb:514:in `down'
/var/www/redmine/lib/redmine/plugin.rb:536:in `migrate_plugin'
/var/www/redmine/lib/redmine/plugin.rb:477:in `migrate'
/var/www/redmine/lib/redmine/plugin.rb:488:in `migrate'
/var/www/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'

Caused by:
ActiveRecord::RecordNotFound: Couldn't find Role with 'id'=all
/var/www/redmine/plugins/redmine_helpdesk/db/migrate/005_add_treat_as_supportclient_to_anonymous.rb:11:in `down'
/var/www/redmine/lib/redmine/plugin.rb:514:in `down'
/var/www/redmine/lib/redmine/plugin.rb:536:in `migrate_plugin'
/var/www/redmine/lib/redmine/plugin.rb:477:in `migrate'
/var/www/redmine/lib/redmine/plugin.rb:488:in `migrate'
/var/www/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)

**Comment by zuoliang365** [comment]
I got the same error, is there any solution?
Thx!
