### ISSUE TITLE
Redmine version 4.1 Compatibility

### ISSUE THREAD

**Issue by rohitthakral** [jfqd/redmine_helpdesk#150]
Hi Guys

Can I collaborate with someone to get this compatible with v4.1 of Redmine?

Thanks
Rohit

**Comment by gainskills** [comment]
I'm using this plugin on Redmine4.1.  What I did to run the plugin is merging all changes in the pull requests.

**Comment by rohitthakral** [comment]
Ok. So I tested the latest version on Redmine 4.1 and here is the first issue:

> MailHandler: an unexpected error occurred when receiving email: undefined method `id' for nil:NilClass

This comes up whenever a ticket is updated using email.

**Comment by rohitthakral** [comment]
ok guys. Got this fixed.

Changed lib/mail_handler_patch.rb line 96 with this:

`if issue.closed? && custom_value.present? && custom_value.value.present?`

instead of 

`if issue.closed? && custom_value.value.present?`
