### ISSUE TITLE
Owner email autofill from predefined user 

### ISSUE THREAD

**Issue by ahamdan1990** [jfqd/redmine_helpdesk#151]
Kindly note that when a predefined-user which is treat as support client and giving that permission in role is adding a new issue the first reply message is not sent to his email instead of that the redmine standard notification is sent.
Noting that if a ticket is opened from an anonymous user via email an automatic response is sent.

**Comment by jfqd** [comment]
This is an intended behaviour of the plugin. You can create a pull request to the Readme if you would like to clarify it :)
