### ISSUE TITLE
Activate Helpdesk plugin on Project basis

### ISSUE THREAD

**Issue by claudiovts** [jfqd/redmine_helpdesk#155]
Hello there! Hope you are all fine!
We have a problem with Helpdesk plugin and Redmine 4.1.
After installing the plugin, we must properly configure all projects with proper automated first response or any email coming from outside will not be deleted from our email server, creating the same issue over and over until the email is manually deleted at the email server inbox.
We have this error:
MailHandler: issue #9890 created by Anonymous
MailHandler: an unexpected error occurred when receiving email: undefined method `value' for nil:NilClass

If we could activate the plugin per project, it would be very nice! 

Our system:
Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.5.8-p224 (2020-03-31) [x86_64-linux]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.13.0
  Git                            2.27.0
  Filesystem                     
Redmine plugins:
  additionals                    2.0.25-master
  redmine_basix                  1.0.0
  redmine_checklists             3.1.16
  redmine_ckeditor               1.2.3
  redmine_custom_js              0.1.0
  redmine_dashboard              2.7.1
  redmine_helpdesk               0.0.18
  redmine_issue_templates        1.0.4
  redmine_lightbox2              0.5.1
  redmine_revision_branches      0.3.2
  redmine_theme_changer          0.3.1
  redmineup_tags                 2.0.8
  sidebar_hide                   0.0.8

Best regards,
Claudio

**Comment by jfqd** [comment]
Fix your mailserver :)
