### ISSUE TITLE
Setting helpdesk-sender-email not working

### ISSUE THREAD

**Issue by obrador** [jfqd/redmine_helpdesk#159]
Hi. I'm using helpdesk with last redmine 4.1 and it seems that setting helpdesk-sender-email does not work. Emails are sent with the main email address set in redmine general settings instead of the per-project email address. Logs does not show any error. Anyone tried this on redmine 4.1?

Thanks in advance.

**Comment by michaelseven** [comment]
Yes, this will only work if your email provided allows email names generation, even tho the email is non existent.
 If I connect Exchange to redmine, I can only use the actual email that I have set in redmine conf, but if I set my own email server in the conf file, I get set what ever name I want in the 'Helpdesk-sender-emial'.
Hope this makes sense.

**Comment by obrador** [comment]
Thanks michel, I use mailjet and I configured it to be able to send emails from different addresses, all them tested and working when set in the main notification email in redmine. But the problem still persist: redmine only sends emails from the address set as main notification email, never with the per-project "helpdesk-sender-email". May it be that the plugin is not compatible with redmine 4.1? am I missing something?

Thanks a lot in advance

**Comment by obrador** [comment]
Hi, it's me again. After some testing, it seem that helpdesk plugin does not work at all, none of the configuration made in project settings affects to the result, just as if helpdesk isn't installed. But it is as long as I can see the configuration options in project settings.

**Comment by michaelseven** [comment]
> Thanks michel, I use mailjet and I configured it to be able to send emails from different addresses, all them tested and working when set in the main notification email in redmine. But the problem still persist: redmine only sends emails from the address set as main notification email, never with the per-project "helpdesk-sender-email". May it be that the plugin is not compatible with redmine 4.1? am I missing something?
> 
> Thanks a lot in advance

hi there,

HelpDesk is not compatible fully with 4.1, that could be the reason :(

**Comment by jfqd** [comment]
Might be. In the Readme it says: "The latest version of this plugin is only compatible with Redmine 4.0.x.".
But you always can send a pull request :)

**Comment by obrador** [comment]
Hi. Tested on 4.0.7 and problem still persists.
