### ISSUE TITLE
helpdesk-sender-email not working on 4.0

### ISSUE THREAD

**Issue by obrador** [jfqd/redmine_helpdesk#161]
Hi. I opened a similar issue  #159, closed because we agreed that helpdeslk was not compatible with redmine 4.1. Now I downgraded redmine to 4.0.7 and the problem persists: emails are sent with the main email address set in redmine general settings instead of the per-project helpdesk-sender-email address. Logs does not show any error. It seems like helpdesk does not work at all. Do I miss something? I've installed it with the normal procedure, no errors. Just it doesn't work.

distro: debian buster
redmine: 4.0.7
redmine_helpdesk: 0.0.18
ruby: 2.5.5
rails: 5.2.4.4
mysql-client: 5.7
mysql-server: 8.0

Edited: I don't know if it's important or not, but the redmine 4.0.7 is not a new installation, it's an upgrade from a 2.5.0 in which the plugin worls like a charm.

**Comment by obrador** [comment]
Hi. I'm getting very frustrated, but I think I miss some small detail on this, and I can't get it work. 

I tried now the plugin on redmine 3.4, using the archive v3.1 version. I can't get redmine to send emails from the email set on helpdesk-sender-email field. I'm sure it's well configured, at least settings are exactly the same than the 2.5.0 version we have on production, but when I try to upgrade it to 3.4, 4.0 or 4.1 this simply doesn't work. 

Any idea would be so much appreciated.

Thanks.

**Comment by jfqd** [comment]
Fixed it with commit c3177d8.
