### ISSUE TITLE
Reply on email from redmine (with [Rogator IT Support - #381]) not udpate issue and goes to Error folder in mailbox.

### ISSUE THREAD

**Issue by dimkaskv** [jfqd/redmine_helpdesk#165]
If some client send email to our ticketsystem (4.0.1.stable) it makes new issue, all right. Client receive confirmation email with number of Issue. But if he try to reply on this mail with saving subject (number for example [Rogator IT Support - #381]) email dont goes to success folder in mailbox (goes to failed) and issue not updates. In receiver we have this configuration:

rake -f /opt/redmine/Rakefile  redmine:email:receive_imap \
        RAILS_ENV="production"                  \
        host=imap.mnet-online.de                \
        port=993                                \
        username=ticket@rogator.de              \
        password=***                    \
        ssl=SSL                                 \
        project=software-support                \
        folder=INBOX                            \
        move_on_success=INBOX.success           \
        move_on_failure=INBOX.failed            \
        no_permission_check=1                   \
        unknown_user=accept                     \
        priority=Hoch
So, looks like hepldesk plugin dont see issue number in subject=( I try all settings from REAMDE, but not success(

**Comment by jfqd** [comment]
This is not a support issue tracker. If you need support you can contact our company.
