### ISSUE TITLE
The "owner-email" field is blank if the user is not anonymous 

### ISSUE THREAD

**Issue by neuking** [jfqd/redmine_helpdesk#166]
When editing issues, if the user is not anonymous, the "owner-email" and "copy-to" fields are always blank. When the Author is anonymous, the owner-email and copy-to fields are correctly completed with the email addresses 

I need for registered users to automatically issue with their e-mails 
can someone help me with this problem? 

Environment:
  Redmine version                4.0.0.stable
  Ruby version                   2.7.4-p191 (2021-07-07) [x86_64-linux-gnu]
  Rails version                  5.2.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.30.2
  Filesystem                     
Redmine plugins:
  redmine_helpdesk               0.0.18
  redmine_people                 1.6.1

**Comment by jfqd** [comment]
This is intended.
