### ISSUE TITLE
Allow use Modern Auth Exchange online Oauth2

### ISSUE THREAD

**Issue by gercastro** [jfqd/redmine_helpdesk#174]
We need allow to use modern auth instead basic auth because Microsoft  Deprecation of Basic authentication in Exchange Online

https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online

**Comment by rohitthakral** [comment]
Anyone interested in collaboration on this?
