### ISSUE TITLE
Change the Reply-to header

### ISSUE THREAD

**Issue by barbazul** [jfqd/redmine_helpdesk#4]
Not sure if this is a general Redmine Issue or if it's a possible feature for the module but, I am running GoogleApps SMTP for redmine through a redmine@... email.

I created a support@... account where I receive all support-related issues and I set up the cron to check that inbox. 

The problem is that the email gets sent from redmine@... because of google policies. 

is there any way to setup a different Reply-to header so when the user clicks "reply" they would reply to support@... and not redmine@... ?

**Comment by charleslcso** [comment]
I'm a bit confused. 

In this case, your per-project custom field has a Title of "mail_from"???
