### ISSUE TITLE
Support for tracking of CC and possibly other e-mail details

### ISSUE THREAD

**Issue by martincizek** [jfqd/redmine_helpdesk#51]
Incoming support request e-mails are often referring to people in CC (e.g. "contact my colleague in CC"), but the CC information is lost when the e-mail is submitted as a ticket.

We'd like to implement an option of CC tracking. And as we want our pull request to succeed, I'd like to agree on the preferred solution:

1. Introducing single per-issue custom attribute called e.g. 'owner-details' with type 'long text', which would contain some details about the original e-mail in "name: value" format on each line. It would contain To (can also contain multiple recipients), Cc, Date (can differ from the issue creation date because of time zones, technical issues, etc.). If the custom attribute is not defined, the email details simply won't be tracked.
2. Introducing 'owner-email-cc' per-issue attribute with type 'text', possibly also 'owner-email-to'. More eventually in future. Again, the attributes would be filled only if they are defined in Redmine.
3. Prepending e-mail details to the text of the first message (similar to 1).

Pros/cons:

1. All email detail information at one place. Multiline attribute may not look nice in the issues (it's not that bad though).
2. Most structured option, but email detail information may be scattered into several attributes (little confusing if user chooses to track several owner-email-* attributes)
3. Looks nice and organized, but e-mail details would be mixed with the issue description. Least structured option.

What do you consider the best solution?

Thank you,
Martin

**Comment by VoronyukM** [comment]
The blockquote ("bq.") have one benefit against of < pre >: if you cite the supportclient's message, Redmine will replace < pre > block by [...], but the "bq." will not, so the client can see at least date of his email.
