### ISSUE TITLE
owner-email field is empty

### ISSUE THREAD

**Issue by ploef** [jfqd/redmine_helpdesk#54]
Hi,

This plugin is exactly what I was looking for except......it's not working. ;-)
I'ḿ using version 2.6.0 of Redmine so that may be the problem. 
The owner-email field stays empty and no mail is send to the sender of the ticket.
Is there something I can do or do I have to be more patient and wait for plugin to be compatible with version 2.6.0. ?

Best regards,
Peter

**Comment by jonnsn** [comment]
I tried to debug this a little and found out that the roles are empty.
But I was not able to find out why yet (not an ruby expert).
This returns an empty array for anonymous user:
issue.author.roles_for_project(issue.project)
After debugging redmines model/user.rb I saw roles_for_project always resolves to last else which simply returns [].

In the diff of branch 2.6 you can see that there was an if logged? in line 327 in the old file
http://www.redmine.org/projects/redmine/repository/diff/branches/2.6-stable/app/models/user.rb?utf8=%E2%9C%93&rev=13873&rev_to=4492
which was removed. As a quick test I tried to add that code again, but it moves my mails to failed-imap-Folder then.
Might be more a redmine-Core issue though....

**Comment by vilppuvuorinen** [comment]
Has anyone been able to reproduce this? I've manually tested functionality against redmine/redmine@662bd633ce0654de466cd07872c415e5c9a8561d (tip of 2.6-stable branch) and this far I haven't been able to reproduce these errors - including the project specific email.

I tried comparing the tip of 2.6-stable to 2.6.0 tagged (https://github.com/redmine/redmine/compare/2.6.0...2.6-stable), but I can't see how those changes could have fixed the issues described here.

**Comment by A-Kasper** [comment]
I've got the same problem. After some trys I figured out that commenting out line 20 and line 34 in mail_handler_patch.rb helps to show the owner adress. this is very dirty and bypasses the user rolecheck, but it's a workaround. I hope this could help to build a real fix. I don't got a clue of ruby. I just checked some try and error things to find out where the problem happens. Maybe someone of you is able to fix it.

**Comment by A-Kasper** [comment]
Seems like the problems come from this changes in Linke 457 following:
http://www.redmine.org/projects/redmine/repository/diff/branches/2.6-stable/app/models/user.rb?utf8=%E2%9C%93&rev=13873&rev_to=12471

**Comment by vilppuvuorinen** [comment]
The source of this change is actually this changeset: http://www.redmine.org/projects/redmine/repository/revisions/13417

@A-Kasper: Have you used the project specific permissions for the anonymous users or are those setting left to defaults?

**Comment by A-Kasper** [comment]
Am 05.03.2015 um 16:14 schrieb Vilppu Vuorinen:
> The source of this change is actually this changeset:
> http://www.redmine.org/projects/redmine/repository/revisions/13417
> 
> @A-Kasper <https://github.com/A-Kasper>: Have you used the project
> specific permissions for the anonymous users or are those setting left
> to defaults?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfqd/redmine_helpdesk/issues/54#issuecomment-77380992>.
> 
 I don't got a clue what the default settings should be and if I ever
changed them. If you would tell me, I could give it a try

**Comment by A-Kasper** [comment]
Am 05.03.2015 um 16:14 schrieb Vilppu Vuorinen:
> The source of this change is actually this changeset:
> http://www.redmine.org/projects/redmine/repository/revisions/13417
> 
> @A-Kasper <https://github.com/A-Kasper>: Have you used the project
> specific permissions for the anonymous users or are those setting left
> to defaults?

For a test I gave ALL rights to the anonymous users. The field remains
empty.

I've attached two screenshots of mine. There you can see the difference
between 2.5 and 2.6. I think these changes are responsible. Someone else
here wrote that his debugging-tests resulted in an [] response. We can
find this in the new changes to  2.6 (line 484). As I already told you:
I don't know the ruby syntax and how to read this code, but i think this
is the part you should look at.

**Comment by vilppuvuorinen** [comment]
I tried adding test: jubicoy/redmine_helpdesk@18942a9673e8d568b593cae9cac9da5ab073be40

The MailHandler patch tests seem to pass with 2.6.0, 2.6.1 and 2.6-stable. Comparing current setup to the fixtures in the referenced commit and sharing logs are next steps.

**Comment by jfqd** [comment]
@vilppuvuorinen: Your tests are looking promising. I would like to include them if you say they are ready. And maybe we can get this on travis, which would make the test for newer Redmine versions easier :)

**Comment by DilipCCS** [comment]
This plugin's owner field is not working with version 2.5.3

**Comment by jfqd** [comment]
@DilipCCS Please do not post your issue on more that one place. #64

**Comment by jfqd** [comment]
Tests are passing for Redmine versions 2.4.7, 2.5.3, 2.6.2 and 3.0.1. Will close this issue for now.
