### ISSUE TITLE
Subject truncates

### ISSUE THREAD

**Issue by asmikhailov** [jfqd/redmine_helpdesk#58]
Mailer create issue with shortenen subject when recieve email with MIME-Encoded email subject. Could it be fixed by plugin?

**Comment by asmikhailov** [comment]
At leasy for me UTF-8 based cyrillic subject truncated

**Comment by mrPsycho** [comment]
this is redmine bug. i already posted it, and wish that you'll post it too at redmine.org

Yaroslav

**Comment by asmikhailov** [comment]
Could you show me the link to issue? Duplicates is not good, otherwise approvement is much better.

**Comment by mrPsycho** [comment]
sure:
https://redmine.org/issues/18170#change-59879

**Comment by jfqd** [comment]
Thanks @mrPsycho for pointing it out, redmine_helpdesk is using this functionality from redmine.
