### ISSUE TITLE
Feature request: Use owner-email also for redmine users...

### ISSUE THREAD

**Issue by astoeffer** [jfqd/redmine_helpdesk#60]
..., i.e watchers, reporter, etc.

For anonymous users the helpdesk-sender-email is used by the plugin.
But if I update an issue, the system wide email address is used for sending emails to redmine users who are watchers or creators of issues.

My which is, that also for redmine users the helpdesk-sender-email can be used.

Andreas

**Comment by jfqd** [comment]
Please read the [CONTRIBUTING](https://github.com/jfqd/redmine_helpdesk/blob/master/CONTRIBUTING.md) file why I close this issue.
