### ISSUE TITLE
Feature request: Incorporate the original text (of the user request) in the emails sent to the user

### ISSUE THREAD

**Issue by gherzig** [jfqd/redmine_helpdesk#61]
The idea is to clarify the email (as received by the user) by incorporating the original text (like in a real reply-to)
Today, if a certain user sends two email, and we put a note on one of those issues, the user just receives some text, the one in the note, but he has no way to know what of the (many) emails he has sent to us.

If he/she could see the original email.....The email received will look like that:
> Dear team:
> We want to add a new item to the menu
> Thanks in advance. 
> Mr. Doom.

Thank you for writing, Mr. Doom. Tomorrow moring i will give you a call and talk about this.
Could that be possible?

Thanks!!
Gerardo

**Comment by jfqd** [comment]
Please read the [CONTRIBUTING](https://github.com/jfqd/redmine_helpdesk/blob/master/CONTRIBUTING.md) file why I close this issue.

**Comment by jfqd** [comment]
This has nothing to do with this plugin and can be achieved within redmine.
