### ISSUE TITLE
Migration issues with PostgreSQL

### ISSUE THREAD

**Issue by vilppuvuorinen** [jfqd/redmine_helpdesk#66]
Current migrations trigger ```PG:DuplicateColumn``` errors if the migrations are run twice. This can cause problems if there happens to be a need to update the plugin migrations in the future.

##### How to reproduce
* Setup postgresql backend
* run ```rake db:migrate```
* run ```rake redmine:plugins:migrate``` twice

##### Caused by
```end_to_owner``` column is added blindly:
https://github.com/jfqd/redmine_helpdesk/blob/7f449ff45/db/migrate/001_create_custom_owner_email_field.rb#L3

MySQLand SQlite3 don't seem to mind this at all.

##### Proposed fix
Add ```column_exists?``` check:
http://stackoverflow.com/a/5958436/2661603

**Comment by jfqd** [comment]
Migrations should never run twice. Rails handles it through the schema_migrations table. But renaming the file with a leading timestamp makes no sense cause this would lead to failing migrations for all. So the ```column_exists?```check should be the way to go.

**Comment by jfqd** [comment]
@vilppuvuorinen Is it fixed yet for you?

**Comment by vilppuvuorinen** [comment]
I also thought that those errors were a bit strange, but I could reproduce them consistently. However, I can't reproduce the errors anymore with or without the change in migrations. I guess it was a temporary error in the postgres confs or something similar.

On the positive side the change does not affect the functionality.
