### ISSUE TITLE
Reduce the email subject to "[#....] subject"

### ISSUE THREAD

**Issue by VoronyukM** [jfqd/redmine_helpdesk#69]
Some users was shocked by the reply contains "[My project - Error #...] (New) My subject"
The subject above may be helpful for developers but for customers it is terrible to understand why "My subject" is converted to the subject. Also status may be changed (New -> Resolved -> Closed) so the customers is not able to sort the emails by subject. And at last in mobile device such subject takes too many space (sometimes it is impossible to read anything from "My subject").
I propose to reduce the subject just to "[#....] subject".
I will do this in my fork.

**Comment by jfqd** [comment]
This is really nothing I would worry about. If you would like to change the term "Error" you can do it easily to "Support" or whatever tracker you want to use.

**Comment by VoronyukM** [comment]
The problem indeed is that subject contains a lot of useless information for client. And if project's name is too long, a useful information (initial e-mail subject) will be out of screen.
I agree that my solution is not universal, but what do you think about an ability of subject customization?

**Comment by vilppuvuorinen** [comment]
If you need this functionality like this use your own fork and keep it up to date to the upstream. Other solution would be to use my fork. Maybe at some point the particular feature could be merged back to this repo, but that is not going to happen anytime soon or even ever.

**Comment by jfqd** [comment]
@VoronyukM I thought about it and I think you are right, that it is unimportant for the supportclient to see the tracker or status in the subject. But the project name need to be part of it. If you change your request to the following line I will pull it.

```subject = "[#{issue.project.name} - ##{issue.id}] #{issue.subject}"```

**Comment by VoronyukM** [comment]
@jfqd I prefer to use [ISSUE-id](http://www.redmine.org/plugins/issue_id) plugin instead. In that case you have the project id and the issue id all-in-one. I have some fixes for that plugin concerning email handling and git commit parsing with issue id's specified in format (e.g. #PROJECT-123). See the project's issue tracker [here](http://projects.andriylesyuk.com/issues/ISSUE-9) and [here](http://projects.andriylesyuk.com/issues/ISSUE-10) (unfortunately the plugin's author prefers svn and it's own redmine instead github).
