### ISSUE TITLE
Send all previous conversations to a supportclient

### ISSUE THREAD

**Issue by VoronyukM** [jfqd/redmine_helpdesk#72]
Now only current answer is sent to a supportclient. But many customers find helpful to keep all conversations in the message body to remember what causes the problem.
I propose with each reply send to a client all previous journal notes created
* with flag "send reply to a client"
* by anonymous

and issue details if issue was created by anonymous.
In that case the reply from redmine_helpdesk will be similar to classical "reply with history" in mail.

As journal notes from supportclient are authored by anonymous it may require to track from, CC (and maybe subject) fields for each customer answer (here #51 the fields tracked only for first customer message).

**Comment by vilppuvuorinen** [comment]
This can be done manually by quoting the previous entry. However, this entry has Anonymous as author and it has to be changed manually if it is deemed necessary.

**Comment by VoronyukM** [comment]
> This can be done manually by quoting the previous entry

Yes, it can. But what if a user sent to you an email with up to 3 pages of conversations and asked you to keep the history? Your issue journal will be polluted by such quoting.
> However, this entry has Anonymous as author and it has to be changed manually if it is deemed necessary.

This will be not necessary if mail_handler tracks the From field like that (see the picture).
It was already implemented in #51 (PR #56), but just only for the first email. In my opinion it is not so hard to do that for all other emails from the client (as option).
![from-cc-tracking](https://cloud.githubusercontent.com/assets/7186304/6943785/ea27ca80-d898-11e4-9df0-12e4bbf85ae7.png)

**Comment by vilppuvuorinen** [comment]
If this is viewed directly from the perspective of the mailer application, the process of fetching the previous messages would be something I am quite reluctant to do. The history is tracked with the journal entries and the dialogue with the supportclient could be mixed with internal messages. In addition, the conversation history is always included with the supportclients messages.

The sensible way to do this would be using the quoting method with following changes:
* changing ```/issue/<id>/quoted?journal_id=<id>``` to replace "Anonymous" with ```owner-email```
* adding javascript that allows collapsing lines from journal notes prefixed with ```>``` and does it by default

The amount of work in these changes is quite large compared to the fact that they only server to make things more convenient.

**Comment by jfqd** [comment]
redmine_helpdesk is a helpdesk plugin. If you have projects with clients who like to have the full history you need to give them an account.

Getting all history mailed back in a journal is a pain in the ass for me as a support person. I always have to delete these parts to make a clean history.

**Comment by VoronyukM** [comment]
> I always have to delete these parts to make a clean history.
Why don't you use core Redmine function "truncate the email after"?
We use such templates:
    Best regards,
    ---- Please reply above this line ----
Second one is better to append in a header not in a footer.
