### ISSUE TITLE
MacroExpander

### ISSUE THREAD

**Issue by vilppuvuorinen** [jfqd/redmine_helpdesk#73]
@jfqd 
I have implemented MacroExpander back  in jubicoy/redmine_helpdesk. I think it could be merged back, but it takes a bit more work due to my refactorings. Because of that I'd like to get some details set before doing anything about it. 

Motivation for the changes would be simplifying the user interface for the macros and removing the cluttered macro expansion from the mailer.

Currently I have User, Issue and Project related macros available and I'm planning on merging the CustomField macros into the same Class. [jubicoy/redmine_helpdesk:macro_expander.rb](https://github.com/jubicoy/redmine_helpdesk/blob/jubicoy/master/lib/macro_expander.rb)

* Which format? %MACRO% or ##macro## (@martincizek)
* Which implementation? Class or Module

**Comment by jfqd** [comment]
Using a MacroExpander class or module is a good idea and making a decision about the format too. But I am not too keen to refactor it as you have done it in #63. Your refactoring looks cleaner, but I think it is easier to understand if we keep the HelpdeskMailer class.

**Comment by vilppuvuorinen** [comment]
I'm intending to rebase or rewrite the MacroExpander on top of the current master without the refactoring. This is why I'm interested about getting the details right before doing anything.

My own preference would be to use the ##macro## format and maybe Module approach against the Class based I have used.

**Comment by vilppuvuorinen** [comment]
@tatarevicova Creating a rake task for replacing macros would not be out of the question. However, I would do it only as a single macro at a time for any given macro. For example all %USER_NAME% macros to ##user-name##. 

I think we have reached a conclusion here:
* MacroExpander is a module.
* It replaces macros formatted as ##macro##.
* I will merge macros from jubicoy fork with macros from #52.
* Macros will be expanded in all fields that currently expand either macros from #52 or the ##issue-id## macro.
* A rake task will be provided for replacing said macros in CustomFields related to this plugin.

**Comment by jfqd** [comment]
@vilppuvuorinen I would be happy to get your pull request :)

**Comment by jfqd** [comment]
Closed by #74 pull request.
