### ISSUE TITLE
Compatible with Redmine 3.0.3?

### ISSUE THREAD

**Issue by nixmomo** [jfqd/redmine_helpdesk#76]
Hi Guys,
is this plugin compatible with redmine 3.0.3?

**Comment by vilppuvuorinen** [comment]
That is most likely the case. Let me create a pull request that runs unit tests against the top of the stack. Approx 15 min.

**Comment by nixmomo** [comment]
Okay, Thanks for your help... ill wait :-)

**Comment by vilppuvuorinen** [comment]
The PR is up. You can check the results at #77. It will take a while.

**Comment by nixmomo** [comment]
Okay, thanks a lot :-)
