### ISSUE TITLE
owner-email field in project configuration not exist

### ISSUE THREAD

**Issue by nixmomo** [jfqd/redmine_helpdesk#78]
To use the helpdesk functionality you need to

add the custom field 'owner-email' to a project in the project configuration

Hello again :-)
With this point in your usage section, i have a problem.
There is no field in the configuration of projects.... must i create it? When yes, how?
Is it a custom text field in section project / user/ticket or anything else?

**Comment by vilppuvuorinen** [comment]
See project settings.

https://github.com/jfqd/redmine_helpdesk/blob/master/CONTRIBUTING.md

**Comment by nixmomo** [comment]
i found it... but it is always anonymus user and not the mail address :-(

**Comment by vilppuvuorinen** [comment]
The tests suggest that the owner-email field is being set correctly. If you are certain that there is nothing wrong with your setup, create an issue about the owner-email being correctly set.
