### ISSUE TITLE
Modularization

### ISSUE THREAD

**Issue by vilppuvuorinen** [jfqd/redmine_helpdesk#81]
Currently the plugin is basically enabled for all projects. Due to the external scripting burden it makes sense because the issues are only received by projects that they are meant for. Nevertheless, what I would like to see is a separate model for the helpdesk feature and implementation as a module that can be enabled or disabled on per project basis.

Provided that there would be a migration path from current release could be implemented as a less backwards compatible "1.0" release. I find CustomField usage just as intrusive as introducing new models.

**Comment by jfqd** [comment]
Do you really think this is a burden? I don´t think so, not even with hundreds of projects. And in my opinion CustomField are exactly for this usage. What would be your solution for that?

**Comment by vilppuvuorinen** [comment]
My vision would be separate, carefully namespaced model for a single project's helpdesk configuration. Such as ```JfqdHelpdesk```. When user wants to add helpdesk functionality to a project an instance of the model would be created and stored into the database. The ability to completely disable the module from projects where it is not needed is the best part of this approach. Usability would also be improved by moving the settings on a separate tab in project settings.

Doing this would seem like adding bulk to a plugin aimed to be as light weight as possible. However, as stated before the new models are not necessarily more intrusive than using CustomFields. The CustomFields are a good solution but the separate model would be a step cleaner. Instead of rows in CustomValues table there would be columns in JfqdHelpdesk table.
