### ISSUE TITLE
supportclient is blank

### ISSUE THREAD

**Issue by w0www** [jfqd/redmine_helpdesk#83]
I recently install this plugin and we send email to my account and the issue is created in my redmine but when i comment the issue i dont see "send email to support".

I try with a fork that active that button always and i see that my supporclient is ()
![support](https://cloud.githubusercontent.com/assets/1654762/8372500/1f739064-1be4-11e5-91f7-e9217599adbf.png)

**Comment by vilppuvuorinen** [comment]
This seems like a recurring topic: #64 and #54 

Could you provide some additional info such as
* Redmine version
* Is the support client field empty also in the issue?

Hiding the checkbox when there is no supportclient seems like default behavior.

**Comment by w0www** [comment]
Redmine version is 2.6.5
suppor client field where is? When i see the issue i dont see the field.

**Comment by w0www** [comment]
The problem was that owner-email field is not assing to type of task (support,errors,enhanced for example). 

I asign the type of task to owner email custom field and now i can see the field. I tested it fetching email.

**Comment by vilppuvuorinen** [comment]
This seem to point towards configuration error. Tests against 2.6.5 [pass](https://travis-ci.org/jfqd/redmine_helpdesk) and 2.6.x has been confirmed as working.

**Comment by w0www** [comment]
FIXED! Please @jfqd  add in installation guide that owner-email custom field have been add to types of issues or activate for always automatically when you active in the project this custom field.
