### ISSUE TITLE
Dont save owner email

### ISSUE THREAD

**Issue by w0www** [jfqd/redmine_helpdesk#85]
When the user exist on DB the owner email is dont save. Example:

User1 is a member of redmine
User1 sent email to example@example.net
Fetching example@example.net
Issue create and the owner email dont save.

--------------------------------------------------------------

If user1 is not member of redmine works fine.

¿Is a bug?

**Comment by vilppuvuorinen** [comment]
Read the README:

> * add the permission 'Treat as supportclient' to all roles you want to be treated as supportclient (the permission is automatically added to the 'Anonymous' role)

**Comment by w0www** [comment]
Ok :D THANKS!
