### ISSUE TITLE
Unable to properly uninstall on Redmine 3.0.4 | ruby 2.2.1 via RVM

### ISSUE THREAD

**Issue by crossz** [jfqd/redmine_helpdesk#92]
Hi jfqd

This plugin seems not work for me (Redmine 3.0.4 | ruby 2.2.1 via RVM), so I tried to uninstall it by using the standard command: "rake redmine:plugins:migrate NAME=redmine_helpdesk VERSION=0 RAILS_ENV=production"

This action aborted caused by the following errors:

== 5 AddTreatAsSupportclientToAnonymous: reverting ============================
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Couldn't find Role with 'id'=all/home/caiex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/relation/finder_methods.rb:324:in `raise_record_not_found_exception!'
/home/caiex/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/relation/finder_methods.rb:444:in`find_one'

Correspondingly those text fields coming along with this plugin can not be removed, while I don't want to get hands dirty by tweak mysql for removing these. 

So could you fix this?

Thanks,
Cross

**Comment by crossz** [comment]
problem should comes from 005_add_treat_as_supportclient_to_anonymous.rb:

  def self.down
    Role.find(:all).each do |r|
      r.remove_permission!(:treat_user_as_supportclient)
    end
  end

**Comment by crossz** [comment]
solved by:

>  def self.down
>    #Role.find(:all).each do |r|
>    #  r.remove_permission!(:treat_user_as_supportclient)
>    #end
>    Role.find(2).remove_permission!(:treat_user_as_supportclient)
>  end

**Comment by vilppuvuorinen** [comment]
I don't think this solution applies if the `:treat_user_as_supportclient` permission has been set to other users than anonymous.

It looks like the root cause is Rails 4.2 incompatibility. The migrations should be part of the test set to ensure compatibility.

**Comment by crossz** [comment]
you are right, Vilp.

I just have only one id who was added this permission. So I manually remove this plugin by the above way.

**Comment by qpratt** [comment]
Old issue, but I had this issue in Redmine 3.3.x. Thanks for the solution.
