### ISSUE TITLE
redmine_helpdesk not working with Redmine 3.0.3

### ISSUE THREAD

**Issue by bdgarg** [jfqd/redmine_helpdesk#93]
Hello Folks, 
I am getting the issue in using redmine_helpdesk on Redmine 3.0.3 deployment. I have deplyed the plugin in redmine, even its showing in Redmine pluging page. But there is not link to activate it. Its not even clickable. Its just redmine_helpdesk name. I have attached the screenshot for same as well. Please assist, if somebody have already faced the similar issue.
Best Regards,
BD Garg 
![image](https://cloud.githubusercontent.com/assets/7338014/8956484/ff9d21a2-3613-11e5-81df-475123989bf3.png)

**Comment by jfqd** [comment]
Please read the [CONTRIBUTING](https://github.com/jfqd/redmine_helpdesk/blob/master/CONTRIBUTING.md) file why I close this issue.

You should read the [Readme](https://github.com/jfqd/redmine_helpdesk/blob/master/README.md) carefully - it is all written up what you need to do to get it work.
