### ISSUE TITLE
 owner-email is functional only with public projects #75  Solution is not working

### ISSUE THREAD

**Issue by ghost** [jfqd/redmine_helpdesk#94]
I am using Redmine 2.4. I have tried all solutions in related owner-email filed. But noone solution is working.
Before 2.4 I am using  1.4 and that time it was working.

Can you help to resolve it.

Also tried solutions for previous ticket.  Dont save owner email #85

**Comment by vilppuvuorinen** [comment]
Have you looked into #75?

**Comment by dilipmadake** [comment]
Yes, I have changed in file as per suggestions into #75

**Comment by vilppuvuorinen** [comment]
Then I'd suggest bumping the version up about 2 minors. 2.6.x should be working.

**Comment by dilipmadake** [comment]
Okay, I will try it.

**Comment by dilipmadake** [comment]
No luck,
I have upgraded to Redmine 2.6.6.stable.14542 with Redmine helpdesk plugin 0.0.15.

Even updated  #75 solutions.

**Comment by Thregarth** [comment]
The solution #75, now it's working

**Comment by jfqd** [comment]
Interestingly all those issue came from people with zero repositories...
