### ISSUE TITLE
Documentation for custom footer syntax needs updating

### ISSUE THREAD

**Issue by jbh** [jfqd/redmine_helpdesk#97]
According to @vilppuvuorinen, the syntax for placeholders has changed in 768605572c9700203df0dad441b7e9b3c9e93995. This can be seen in the commit to `lib/macro_expander.rb`. I plan on updating the documentation with all the placeholders available and with better references to their nature this weekend. I just wanted to make sure there was an issue to track for it.

**Comment by jfqd** [comment]
Thank you for pointing it out! Documentation was fixed by issue #96
